"""Public Codex protocol model exports for type annotations and matching."""

from __future__ import annotations

from pydantic import BaseModel, ConfigDict

from .generated.v2_all import (
    Account,
    AccountLoginCompletedNotification,
    ApprovalsReviewer,
    AskForApproval,
    CancelLoginAccountResponse,
    CancelLoginAccountStatus,
    CollaborationMode,
    CollaborationModeListResponse,
    ConfigBatchWriteParams,
    ConfigEdit,
    ConfigReadResponse,
    ConfigRequirementsReadResponse,
    ConfigWriteResponse,
    ExperimentalFeatureEnablementSetResponse,
    ExperimentalFeatureListResponse,
    ExternalAgentConfigDetectResponse,
    ExternalAgentConfigImportHistoriesReadResponse,
    ExternalAgentConfigImportResponse,
    FsChangedNotification,
    FsCopyResponse,
    FsCreateDirectoryResponse,
    FsGetMetadataResponse,
    FsReadDirectoryResponse,
    FsReadFileResponse,
    FsRemoveResponse,
    FsUnwatchResponse,
    FsWatchResponse,
    FsWriteFileResponse,
    FuzzyFileSearchResult,
    GetAccountResponse,
    ListMcpServerStatusResponse,
    McpResourceReadResponse,
    McpServerRefreshResponse,
    McpServerStatusDetail,
    McpServerToolCallResponse,
    MemoryResetResponse,
    MergeStrategy,
    ModelListResponse,
    ModelProviderCapabilitiesReadResponse,
    Personality,
    PlanType,
    PluginSkillReadResponse,
    Project,
    ProjectCreateResponse,
    ProjectDeleteResponse,
    ProjectImportResponse,
    ProjectListResponse,
    ProjectMoveResponse,
    ProjectReadResponse,
    ProjectRoot,
    ProjectSortKey,
    ProjectUpdateResponse,
    QueuedSubmission,
    ReasoningEffort,
    ReasoningSummary,
    SandboxMode,
    SandboxPolicy,
    SkillsConfigWriteResponse,
    SkillsExtraRootsSetResponse,
    SkillsListResponse,
    SortDirection,
    ThreadArchiveResponse,
    ThreadCompactStartResponse,
    ThreadDeleteResponse,
    ThreadGoalClearResponse,
    ThreadGoalGetResponse,
    ThreadGoalSetResponse,
    ThreadGoalStatus,
    ThreadInjectItemsResponse,
    ThreadItem,
    ThreadItemsListResponse,
    ThreadListCwdFilter,
    ThreadListResponse,
    ThreadLoadedListResponse,
    ThreadMemoryMode,
    ThreadMemoryModeSetResponse,
    ThreadMetadataGitInfoUpdateParams,
    ThreadMetadataUpdateResponse,
    ThreadQueueAddResponse,
    ThreadQueueDeleteResponse,
    ThreadQueueListResponse,
    ThreadQueueReorderResponse,
    ThreadQueueStartResponse,
    ThreadQueueUpdateResponse,
    ThreadReadResponse,
    ThreadRevertResponse,
    ThreadSearchOccurrencesResponse,
    ThreadSearchResponse,
    ThreadSection,
    ThreadSectionAppearance,
    ThreadSectionCreateResponse,
    ThreadSectionDeleteResponse,
    ThreadSectionListResponse,
    ThreadSectionMoveResponse,
    ThreadSectionUpdateResponse,
    ThreadSetNameResponse,
    ThreadSettingsUpdateResponse,
    ThreadSortKey,
    ThreadSource,
    ThreadSourceKind,
    ThreadStartSource,
    ThreadTokenUsage,
    ThreadTokenUsageUpdatedNotification,
    ThreadTurnsListResponse,
    ThreadUnsubscribeResponse,
    Turn,
    TurnCompletedNotification,
    TurnEnvironmentParams,
    TurnError,
    TurnInterruptResponse,
    TurnItemsView,
    TurnSettingsUpdateResponse,
    TurnStatus,
    TurnSteerResponse,
    TurnToolOutput,
)
from .models import InitializeResponse, JsonObject, Notification


class FuzzyFileSearchResponse(BaseModel):
    """Wire response for `fuzzyFileSearch`; omitted by the current schema codegen."""

    model_config = ConfigDict(populate_by_name=True)
    files: list[FuzzyFileSearchResult]


class FuzzyFileSearchSessionStartResponse(BaseModel):
    model_config = ConfigDict(extra="allow", populate_by_name=True)


class FuzzyFileSearchSessionUpdateResponse(BaseModel):
    model_config = ConfigDict(extra="allow", populate_by_name=True)


class FuzzyFileSearchSessionStopResponse(BaseModel):
    model_config = ConfigDict(extra="allow", populate_by_name=True)


__all__ = [
    "Account",
    "AccountLoginCompletedNotification",
    "ApprovalsReviewer",
    "AskForApproval",
    "CancelLoginAccountResponse",
    "CancelLoginAccountStatus",
    "CollaborationMode",
    "CollaborationModeListResponse",
    "ConfigBatchWriteParams",
    "ConfigEdit",
    "ConfigReadResponse",
    "ConfigRequirementsReadResponse",
    "ConfigWriteResponse",
    "ExperimentalFeatureEnablementSetResponse",
    "ExperimentalFeatureListResponse",
    "ExternalAgentConfigDetectResponse",
    "ExternalAgentConfigImportHistoriesReadResponse",
    "ExternalAgentConfigImportResponse",
    "FsChangedNotification",
    "FsCopyResponse",
    "FsCreateDirectoryResponse",
    "FsGetMetadataResponse",
    "FsReadDirectoryResponse",
    "FsReadFileResponse",
    "FsRemoveResponse",
    "FsUnwatchResponse",
    "FsWatchResponse",
    "FsWriteFileResponse",
    "FuzzyFileSearchResponse",
    "FuzzyFileSearchResult",
    "FuzzyFileSearchSessionStartResponse",
    "FuzzyFileSearchSessionStopResponse",
    "FuzzyFileSearchSessionUpdateResponse",
    "GetAccountResponse",
    "InitializeResponse",
    "JsonObject",
    "ListMcpServerStatusResponse",
    "McpResourceReadResponse",
    "McpServerRefreshResponse",
    "McpServerStatusDetail",
    "McpServerToolCallResponse",
    "MemoryResetResponse",
    "MergeStrategy",
    "ModelListResponse",
    "ModelProviderCapabilitiesReadResponse",
    "Notification",
    "Personality",
    "PlanType",
    "PluginSkillReadResponse",
    "Project",
    "ProjectCreateResponse",
    "ProjectDeleteResponse",
    "ProjectImportResponse",
    "ProjectListResponse",
    "ProjectMoveResponse",
    "ProjectReadResponse",
    "ProjectRoot",
    "ProjectSortKey",
    "ProjectUpdateResponse",
    "QueuedSubmission",
    "ReasoningEffort",
    "ReasoningSummary",
    "SandboxMode",
    "SandboxPolicy",
    "SkillsConfigWriteResponse",
    "SkillsExtraRootsSetResponse",
    "SkillsListResponse",
    "SortDirection",
    "ThreadArchiveResponse",
    "ThreadCompactStartResponse",
    "ThreadDeleteResponse",
    "ThreadGoalClearResponse",
    "ThreadGoalGetResponse",
    "ThreadGoalSetResponse",
    "ThreadGoalStatus",
    "ThreadInjectItemsResponse",
    "ThreadItem",
    "ThreadItemsListResponse",
    "ThreadListCwdFilter",
    "ThreadListResponse",
    "ThreadLoadedListResponse",
    "ThreadMemoryMode",
    "ThreadMemoryModeSetResponse",
    "ThreadMetadataGitInfoUpdateParams",
    "ThreadMetadataUpdateResponse",
    "ThreadQueueAddResponse",
    "ThreadQueueDeleteResponse",
    "ThreadQueueListResponse",
    "ThreadQueueReorderResponse",
    "ThreadQueueStartResponse",
    "ThreadQueueUpdateResponse",
    "ThreadReadResponse",
    "ThreadRevertResponse",
    "ThreadSearchOccurrencesResponse",
    "ThreadSearchResponse",
    "ThreadSection",
    "ThreadSectionAppearance",
    "ThreadSectionCreateResponse",
    "ThreadSectionDeleteResponse",
    "ThreadSectionListResponse",
    "ThreadSectionMoveResponse",
    "ThreadSectionUpdateResponse",
    "ThreadSetNameResponse",
    "ThreadSettingsUpdateResponse",
    "ThreadSortKey",
    "ThreadSource",
    "ThreadSourceKind",
    "ThreadStartSource",
    "ThreadTokenUsage",
    "ThreadTokenUsageUpdatedNotification",
    "ThreadTurnsListResponse",
    "ThreadUnsubscribeResponse",
    "Turn",
    "TurnCompletedNotification",
    "TurnEnvironmentParams",
    "TurnError",
    "TurnInterruptResponse",
    "TurnItemsView",
    "TurnSettingsUpdateResponse",
    "TurnStatus",
    "TurnSteerResponse",
    "TurnToolOutput",
]
